FROM node:18-alpine

RUN apk add chromium

WORKDIR /app

ENV CHROME_BIN=/usr/bin/chromium-browser

COPY *.json .
COPY karma.conf.js .

RUN npm i

COPY src/ ./src/

CMD ["npm", "run", "start", "--host", "0.0.0.0"]
